services:
  allhands22:
    image: "${TESTING_IMAGE}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: /healthchecks/postgres-healthcheck
      interval: "10s"
      timeout: "5s"
      retries: 6
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      allhands22:
        condition: service_started
      postgres:
        condition: service_healthy
    # run all your tests here against the allhands22 service
    command: >
      sh -c "echo 'Running tests...';
             curl -v --fail http://allhands22:80 || (echo 'Curl failed'; exit 1)"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"